### ISSUE TITLE
Different standards behind feature flags

### ISSUE THREAD

**Issue by coastalwhite** [inejge/pwhash#19]
Ideally, we should be able to select only the hashing standards we need with feature flags. This can reduce compile times. The `default-features` could still be all the standards, but if you specifically wanted to reduce the dependencies and compile time, you could. This should not cause any significant SemVer change and therefore could just be published as 1.0.1.

**Comment by inejge** [comment]
The idea of placing different hashing algorithms behind their own feature flags has already been floated in #16, but I'm still against it for the same reasons, so I'm going to close the issue as WONTFIX.

**Comment by coastalwhite** [comment]
Ah okay. I didn't see that issue.
