### ISSUE TITLE
Tracking issue for migration from rust-crypto to supported crates

### ISSUE THREAD

**Issue by inejge** [inejge/pwhash#4]
Since rust-crypto is unmaintained, pwhash should probably be migrated away from using it for all digest and encryption algorithms (except DES, which is in-tree). There are independent crates for MD5, SHA1 and SHA2. There is nothing that I know of for bcrypt, so I'll probably move it in-tree from rust-crypto.

- [x] MD5
- [x] SHA1
- [x] SHA2
- [x] bcrypt

**Comment by newpavlov** [comment]
Take a look at [RustCrypto](https://github.com/RustCrypto) organization. It has all hash functions you need and DES implementation too. (though not yet published) There is also a [bcrypt](https://github.com/RustCrypto/rust-crypto-decoupled/tree/master/etc/bcrypt) crate, but it will need a bit of work.

**Comment by inejge** [comment]
Revisited for v0.2.0: bcrypt is still missing in RustCrypto, so I see no pressing reason to proceed with porting.

**Comment by newpavlov** [comment]
You can use @Keats [`bcrypt`](https://github.com/Keats/rust-bcrypt) crate, it's not part of RustCrypto (though I will be happy to see it change), but it does the job.

**Comment by inejge** [comment]
Thanks to @andy128k, the migration is now complete, so I'm closing this.
